package com.xebialabs.xlrelease.udm.reporting.repository

import com.xebialabs.xlrelease.udm.reporting.{Deployment, DeploymentHistory}


trait DeploymentRepository {

  def create(deployment: Deployment): Unit

  def update(original: Deployment, updated: Deployment)

  def delete(deploymentId: String): Unit

  def exists(deploymentId: String): Boolean

  def findById(deploymentId: String): Option[Deployment]

  def findByTaskId(taskId: String): Seq[Deployment]

  def findHistoryById(deploymentId: String): Seq[DeploymentHistory]

  def deleteAutoGeneratedDeployments(taskId: String): Unit
}

